In [1]:
import os 
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import tensorflow as tf
physical_devices = tf.config.list_physical_devices('GPU')
print('Physical Devices', physical_devices)
tf.config.experimental.set_memory_growth(physical_devices[0], True)

Physical Devices [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


### Initialization of tensors

#### Declaring basic tensors

In [2]:
x = tf.constant(4)
print(x)

tf.Tensor(4, shape=(), dtype=int32)


The shape of the constant can be defined using shape parameters

In [3]:
x = tf.constant(4., shape=(1, 1))
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


The data type of the tensor can be defined using dtype parameter

In [4]:
x = tf.constant(4., shape=(1, 1), dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


To declare matrices, just provide 2-dim list

In [5]:
x = tf.constant([
    [1, 2, 4],
    [4, 5, 6]
])
print(x)

tf.Tensor(
[[1 2 4]
 [4 5 6]], shape=(2, 3), dtype=int32)


You can define the shape of the constant using the shape parameter as above

In [6]:
x = tf.constant([
    [1, 2, 4],
    [4, 5, 6]
], shape=(1, 2, 3))
print(x)

tf.Tensor(
[[[1 2 4]
  [4 5 6]]], shape=(1, 2, 3), dtype=int32)


tf.ones accepts a tuple that contains the shape of the matrix. The matrix will be full of ones.

In [7]:
x = tf.ones((3, 3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


tf.zeros accepts a tuple that contains the shape of the matrix. The matrix will be full of ones.

In [8]:
x = tf.zeros((2, 3))
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


tf.eye accepts a single number as parameter and provides a nxn Identity matrix

In [9]:
x = tf.eye(3)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


#### Declaring tensors with random values

tf.random.normal generates a tensor and fills them with numbers sampled from a Normal Distribution. It accepts a tuple as input which should contain the shape of the matrix

In [10]:
x = tf.random.normal((2, 3))
print(x)

tf.Tensor(
[[-0.4364522  -1.4478421   0.48437837]
 [ 0.30637914 -0.38041568 -0.52069294]], shape=(2, 3), dtype=float32)


You can also define the mean and standard deviation of the normal distribution from which the numbers for the matrix should be sampled from. 

In [11]:
x = tf.random.normal((2, 3), mean=0, stddev=1)
print(x)

tf.Tensor(
[[-0.58074695 -0.45162988  1.2388467 ]
 [ 1.1145473   0.9707474  -1.7167132 ]], shape=(2, 3), dtype=float32)


tf.random.uniform generates a tensor and fills them with numbers sampled from a Uniform Distribution. It accepts a tuple as input which should contain the shape of the matrix. It accepts three parameters, the shape (first param), the minval and maxval which defines the minimum and maximum values for the uniform distribution

In [12]:
x = tf.random.uniform((1, 3), minval=0, maxval=1)
print(x)

tf.Tensor([[0.69552445 0.49353445 0.5680809 ]], shape=(1, 3), dtype=float32)


This is similar to the range function in python

In [13]:
x = tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [14]:
x = tf.range(start=1, limit=10, delta=2)
print(x)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


#### Changing the datatype of an existing tensor

The tf.cast method accepts two parameters, the tensor itself and the dtype.

In [15]:
x = tf.cast(x, dtype=tf.float64)
print(x)

tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


tf.float -> 16, 32, 64 ... tf.int -> 8, 16, 42, 64 ... tf.bool


### Mathematical operations

In [16]:
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])

#### Add (Element wise)

In [17]:
z = tf.add(x, y)
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [18]:
z = x + y
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


#### Subtract (Element wise)

In [19]:
z = tf.subtract(x, y)
print(z)

tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


In [20]:
z = x - y
print(z)

tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


#### Divide (element wise)

In [21]:
z = tf.divide(x, y)
print(z)

tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


In [22]:
z = x/y
print(z)

tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


#### Multiply (element wise)

In [23]:
z = tf.multiply(x, y)
print(z)

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


In [24]:
z = x * y
print(z)

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


#### Dot product between vectors

In [25]:
z = tf.tensordot(x, y, axes = 1)
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [26]:
z = tf.reduce_sum(x*y, axis=0)
print(z)

tf.Tensor(46, shape=(), dtype=int32)


#### Element wise power

In [27]:
z = x**5
print(z)

tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


#### Matrix multiplication

In [29]:
x = tf.random.normal((2, 3))
y = tf.random.normal((3, 4))

In [30]:
z = tf.matmul(x, y)
print(z)

tf.Tensor(
[[-0.32164192  0.37211114  0.58822286 -1.0153505 ]
 [-3.3202138   1.1921885   1.0310276  -3.4116802 ]], shape=(2, 4), dtype=float32)


In [31]:
z = x @ y
print(z)

tf.Tensor(
[[-0.32164192  0.37211114  0.58822286 -1.0153505 ]
 [-3.3202138   1.1921885   1.0310276  -3.4116802 ]], shape=(2, 4), dtype=float32)


### Indexing

In [32]:
x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])

In [34]:
print(x[:])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)


In [35]:
print(x[1:])

tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)


In [36]:
print(x[1:3])

tf.Tensor([1 1], shape=(2,), dtype=int32)


In [37]:
print(x[::2])

tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)


In [38]:
print(x[::-1])

tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


In [39]:
indices = tf.constant([0, 3])
x_ind = tf.gather(x, indices)
print(x_ind)

tf.Tensor([0 2], shape=(2,), dtype=int32)


In [40]:
x = tf.constant([
    [1, 2],
    [3, 4], 
    [5, 6]
])

In [41]:
print(x[0, :])

tf.Tensor([1 2], shape=(2,), dtype=int32)


In [42]:
print(x[0:2, :])

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [43]:
print(x[0:2])

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


### Reshaping

In [44]:
x = tf.range(9)

In [45]:
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [47]:
x_ = tf.reshape(x, (3, 3))
print(x_)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [50]:
x_t = tf.transpose(x, perm=[1, 0])
print(x_t)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
